version: '3'
services:
    nginx:
        image: 'docker.io/nginx'
        ports:
            - 8080:80
        volumes:
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
            - './..:/usr/share/nginx/html'
        depends_on:
            - fpm
    fpm:
        image: 'docker.io/php:8.1-fpm-alpine'
        volumes:
            - './..:/usr/share/nginx/html'
    mariadb:
        image: 'docker.io/mariadb/server'
        ports:
            - '33066:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './db:/var/lib/mysql'